wandb_version: 1

seed:
  desc: null
  value: 42
epochs:
  desc: null
  value: 3
model_name:
  desc: null
  value: microsoft/deberta-v3-base
train_batch_size:
  desc: null
  value: 8
valid_batch_size:
  desc: null
  value: 16
max_length:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 1.0e-05
scheduler:
  desc: null
  value: CosineAnnealingLR
min_lr:
  desc: null
  value: 1.0e-06
T_max:
  desc: null
  value: 500
weight_decay:
  desc: null
  value: 1.0e-06
n_fold:
  desc: null
  value: 3
n_accumulate:
  desc: null
  value: 1
num_classes:
  desc: null
  value: 2
device:
  desc: null
  value: cuda:0
hash_name:
  desc: null
  value: kmyc4k23vc47
_wandb_kernel:
  desc: null
  value: deb
tokenizer:
  desc: null
  value: "DebertaV2TokenizerFast(name_or_path='microsoft/deberta-v3-base', vocab_size=128000,\
    \ model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right',\
    \ truncation_side='right', special_tokens={'bos_token': '[CLS]', 'eos_token':\
    \ '[SEP]', 'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token':\
    \ '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={\n\
    \t0: AddedToken(\"[PAD]\", rstrip=False, lstrip=False, single_word=False, normalized=False,\
    \ special=True),\n\t1: AddedToken(\"[CLS]\", rstrip=False, lstrip=False, single_word=False,\
    \ normalized=False, special=True),\n\t2: AddedToken(\"[SEP]\", rstrip=False, lstrip=False,\
    \ single_word=False, normalized=False, special=True),\n\t3: AddedToken(\"[UNK]\"\
    , rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),\n\
    \t128000: AddedToken(\"[MASK]\", rstrip=False, lstrip=False, single_word=False,\
    \ normalized=False, special=True),\n}"
group:
  desc: null
  value: kmyc4k23vc47-Baseline
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710845178.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 13
      - 15
      - 16
      - 23
      4: 3.11.3
      5: 0.16.4
      6: 4.38.2
      8:
      - 1
      - 5
      13: linux-x86_64
